service: cleverorc-monster-search

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:aws:s3:::cleverorc/pathfinder/allCreatures.json"

functions:
  monsterSearch:
    memorySize: 128
    handler: src/shaefer/monsterSearch.queryByCR
    events:
      - http:
          path: shaefer/cr/{crVal}/{operator}
          method: get
          cors: true